# Generated by Django 2.0.1 on 2018-01-13 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ImgApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='nowhere/nothing.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='photo', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='owner_ref',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 15, 5, 37, 177839, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
