# Generated by Django 2.0.1 on 2018-01-13 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0002_auto_20180113_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 13, 15, 15, 14, 316261, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
