# Generated by Django 2.0.1 on 2018-01-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0003_auto_20180113_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='owner_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
    ]
