# Generated by Django 2.0.1 on 2018-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0004_auto_20180113_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='app_photos'),
        ),
    ]
