# Generated by Django 2.0.1 on 2018-01-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgApp', '0005_auto_20180113_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='description',
        ),
    ]
